/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Faculty;

import java.sql.Connection; 
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException; 

import net.proteanit.sql.DbUtils;
import static Student.USM_MAIN_INTERFACE.jDesktopPane2;

/**
 *
 * @author KAVINDI
 */
public class Subject extends javax.swing.JInternalFrame {
            Connection con = null;
            PreparedStatement pst = null;
            FacultyManagement sub;
            ResultSet rs = null;
    /**
     * Creates new form Subject
     */
    public Subject() {
        initComponents();
        //connect to DB
       con = DBconnect.connect();
         
       
    }
    
    
    
    public void tableload(){
        try{
         String sql = "SELECT subject_id,subject_name,lecturer_incharge,grade_point FROM subject";
         pst = con.prepareStatement(sql);
         rs = pst.executeQuery();
         jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                 
        }
        catch (Exception e){
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        subjectid = new javax.swing.JTextField();
        gradepoint = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        subjectName = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        subjectID = new javax.swing.JLabel();
        Delete_btn = new javax.swing.JButton();
        lecturerIncharge = new javax.swing.JLabel();
        Update_btn = new javax.swing.JButton();
        gradePoint = new javax.swing.JLabel();
        Add_btn = new javax.swing.JButton();
        subjectname = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Reset_btn = new javax.swing.JButton();
        lec = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(1354, 522));
        setNormalBounds(new java.awt.Rectangle(0, 0, 116, 0));
        setPreferredSize(new java.awt.Dimension(1350, 502));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(1354, 382));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 382));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SUBJECT");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        subjectid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subjectid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        subjectid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectidActionPerformed(evt);
            }
        });

        gradepoint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gradepoint.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_Back_131811.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        subjectName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subjectName.setForeground(new java.awt.Color(255, 255, 255));
        subjectName.setText("SUBJECT NAME               :");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        subjectID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subjectID.setForeground(new java.awt.Color(255, 255, 255));
        subjectID.setText("SUBJECT ID                    :");

        Delete_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        Delete_btn.setText("DELETE");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });

        lecturerIncharge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lecturerIncharge.setForeground(new java.awt.Color(255, 255, 255));
        lecturerIncharge.setText("LECTURER INCHARGE   : ");

        Update_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit.png"))); // NOI18N
        Update_btn.setText("UPDATE");
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        gradePoint.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gradePoint.setForeground(new java.awt.Color(255, 255, 255));
        gradePoint.setText("GRADE POINT                 :");

        Add_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        Add_btn.setText("ADD");
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });

        subjectname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subjectname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        Reset_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reset_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        Reset_btn.setText("RESET");

        lec.setEditable(true);
        lec.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select a lecturer --", "Dr.Disanayaka D.L.D", "Mr.Dewanarayana D.S.K", " " }));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "subject_id", "subject_name", "lecturer_incharge", "grade_point"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(Add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(Reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(subjectID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(subjectName, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(gradePoint, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(lecturerIncharge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(subjectid)
                            .addComponent(subjectname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gradepoint, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lec, javax.swing.GroupLayout.Alignment.LEADING, 0, 421, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(subjectid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(subjectname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lecturerIncharge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lec, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gradePoint, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gradepoint, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete_btn)
                    .addComponent(Add_btn)
                    .addComponent(Update_btn)
                    .addComponent(Reset_btn))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1352, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed
        // TODO add your handling code here:

        String subjectID = subjectid.getText().trim();
        String subjectName = subjectname.getText();
        String lecturerIncharge = lec.getSelectedItem().toString();
        String gradePoint = gradepoint.getText();
        try{
            ////            System.out.println(subjectID+ subjectName+lecturerincharge+gradePoint);
            ////            System.out.println(subjectName);
            //            String q = "INSERT INTO subject (subject_id,subject_name,lecturer_incharge,grade_point) values ('"+ subjectID +"','"+ subjectName +"','"+ lecturerincharge +"','"+ gradePoint +"')";
            //            //String q = "insert into subject values(1,null,null,null)";
            ////           String q = "INSERT INTO `subject` (`subject_id`, `subject_name`, `lecturer_incharge`, `grade_point`) VALUES (NULL, 'subjectName', 'lecturerincharge', 'gradePoint')";
            ////            pst = con.prepareStatement(q);
            ////            pst.execute();

            DBconnect.connect().createStatement().executeUpdate("INSERT INTO `subject` (`subject_id`, `subject_name`, `lecturer_incharge`, `grade_point`) VALUES ('"+ subjectID +"', '"+ subjectName +"', 'Dr.Disanayaka D.L.D', '"+ gradePoint +"')");
            JOptionPane.showMessageDialog(null, "Successfully DONE");
            tableload();
        }
        catch (Exception e){
        }

    }//GEN-LAST:event_Add_btnActionPerformed

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
        // TODO add your handling code here:
        String subjectID = subjectid.getText().trim();
        String subjectName = subjectname.getText();
        String lecturerIncharge = lec.getSelectedItem().toString();
        String gradePoint = gradepoint.getText();

        try{
            DBconnect.connect().createStatement().executeUpdate("UPDATE `subject` SET `subject_id` = '"+ subjectID +"', `subject_name` = '"+ subjectName +"', `lecturer_incharge` = 'Dr.Disanayaka D.L.D', `grade_point` = '"+ gradePoint +"' WHERE `subject`.`subject_id` = '"+ subjectID +"'");
            JOptionPane.showMessageDialog(null, "Successfully DONE");

        }
        catch (Exception e){
            //             e.printStackTrace();

        }

    }//GEN-LAST:event_Update_btnActionPerformed

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
        // TODO add your handling code here:

        String subjectID = subjectid.getText().trim();
        String subjectName = subjectname.getText();
        String lecturerIncharge = lec.getSelectedItem().toString();
        String gradePoint = gradepoint.getText();

        try{
            DBconnect.connect().createStatement().executeUpdate(" DELETE FROM `subject` WHERE `subject`.`subject_id` = '"+ subjectID +"' ");

        }
        catch (Exception e){
            //             e.printStackTrace();

        }

    }//GEN-LAST:event_Delete_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //          FacultyManagement f1 = new FacultyManagement();
        //          f1.setVisible(true);
        //          this.dispose();

        if (f1== null) {

            jDesktopPane2.removeAll();
            FacultyManagement f1 = new FacultyManagement ();
            jDesktopPane2.add(f1).setVisible(true);

        } else {

            jDesktopPane2.removeAll();
            jDesktopPane2.add(f1).setVisible(true);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void subjectidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectidActionPerformed

  FacultyManagement f1;
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn;
    private javax.swing.JButton Delete_btn;
    private javax.swing.JButton Reset_btn;
    private javax.swing.JButton Update_btn;
    private javax.swing.JLabel gradePoint;
    private javax.swing.JTextField gradepoint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> lec;
    private javax.swing.JLabel lecturerIncharge;
    private javax.swing.JLabel subjectID;
    private javax.swing.JLabel subjectName;
    private javax.swing.JTextField subjectid;
    private javax.swing.JTextField subjectname;
    // End of variables declaration//GEN-END:variables
}
