/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

//import employee.EmpHome;
//import project40.FacultyManagement;
import EmpManagement.EmpHome;
import finance.Finance_Home;
import Faculty.FacultyManagement;
import Login.UserLogin;
import static Student.USM_MAIN_INTERFACE.jDesktopPane2;

/**
 *
 * @author perer
 */
public class Home_Buttons_Interface extends javax.swing.JInternalFrame {

    /**
     * Creates new form Home_Buttons_Interface
     */
    public Home_Buttons_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        faculty_btn = new javax.swing.JButton();
        Employee_btn = new javax.swing.JButton();
        student_btn = new javax.swing.JButton();
        finance_btn = new javax.swing.JButton();
        admin_btn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(1354, 522));
        setPreferredSize(new java.awt.Dimension(1354, 522));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        faculty_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        faculty_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/school (2).png"))); // NOI18N
        faculty_btn.setText("FACULTY");
        faculty_btn.setToolTipText("FACULTY");
        faculty_btn.setBorder(new javax.swing.border.MatteBorder(null));
        faculty_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        faculty_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        faculty_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faculty_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 57;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 9, 0, 0);
        jPanel1.add(faculty_btn, gridBagConstraints);

        Employee_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Employee_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/employee.png"))); // NOI18N
        Employee_btn.setText("EMPLOYEE");
        Employee_btn.setToolTipText("EMPLOYEE");
        Employee_btn.setBorder(new javax.swing.border.MatteBorder(null));
        Employee_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Employee_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Employee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 57;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(112, 9, 0, 0);
        jPanel1.add(Employee_btn, gridBagConstraints);

        student_btn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        student_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Student-4.png"))); // NOI18N
        student_btn.setText("STUDENT");
        student_btn.setToolTipText("STUDENT");
        student_btn.setBorder(new javax.swing.border.MatteBorder(null));
        student_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        student_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        student_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 404;
        gridBagConstraints.ipady = 161;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 22, 0, 0);
        jPanel1.add(student_btn, gridBagConstraints);

        finance_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        finance_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cash.png"))); // NOI18N
        finance_btn.setText("FINANCE");
        finance_btn.setToolTipText("FINANCE");
        finance_btn.setBorder(new javax.swing.border.MatteBorder(null));
        finance_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        finance_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        finance_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finance_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 18, 0, 10);
        jPanel1.add(finance_btn, gridBagConstraints);

        admin_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        admin_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer-service.png"))); // NOI18N
        admin_btn.setText("ADMIN");
        admin_btn.setToolTipText("ADMIN");
        admin_btn.setBorder(new javax.swing.border.MatteBorder(null));
        admin_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        admin_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        admin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(113, 18, 0, 10);
        jPanel1.add(admin_btn, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void student_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_btnActionPerformed

        try {
            if (s3 == null) {
                jDesktopPane2.removeAll();
                UserLogin s1 = new UserLogin();
                jDesktopPane2.add(s1).setVisible(true);
            } else {
                jDesktopPane2.removeAll();
                jDesktopPane2.add(s3).setVisible(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_student_btnActionPerformed
    FacultyManagement fm1;
    private void faculty_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faculty_btnActionPerformed

        if (s3 == null) {
            jDesktopPane2.removeAll();
            UserLogin f1 = new UserLogin();
            jDesktopPane2.add(f1).setVisible(true);
        } else {
            jDesktopPane2.removeAll();
            jDesktopPane2.add(s3).setVisible(true);
        }

    }//GEN-LAST:event_faculty_btnActionPerformed

    private void Employee_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_btnActionPerformed

        if (s3 == null) {
            jDesktopPane2.removeAll();
            UserLogin e1 = new UserLogin();
            jDesktopPane2.add(e1).setVisible(true);
        } else {
            jDesktopPane2.removeAll();
            jDesktopPane2.add(s3).setVisible(true);
        }

    }//GEN-LAST:event_Employee_btnActionPerformed

    private void finance_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finance_btnActionPerformed

        if (s3 == null) {
            jDesktopPane2.removeAll();
            UserLogin f1 = new UserLogin();
            jDesktopPane2.add(f1).setVisible(true);
        } else {
            jDesktopPane2.removeAll();
            jDesktopPane2.add(s3).setVisible(true);
        }
    }//GEN-LAST:event_finance_btnActionPerformed

    private void admin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_btnActionPerformed

        try {
            if (s3 == null) {
                jDesktopPane2.removeAll();
                UserLogin log = new UserLogin();
                jDesktopPane2.add(log).setVisible(true);
            } else {
                jDesktopPane2.removeAll();
                jDesktopPane2.add(s3).setVisible(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_admin_btnActionPerformed

    UserLogin s3;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Employee_btn;
    private javax.swing.JButton admin_btn;
    private javax.swing.JButton faculty_btn;
    private javax.swing.JButton finance_btn;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JButton student_btn;
    // End of variables declaration//GEN-END:variables
}
