/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finance;

import static Student.USM_MAIN_INTERFACE.jDesktopPane2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Yelani
 */
public class Finance_Expenses extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Finance_Expenses
     */
    public Finance_Expenses() {
        initComponents();

        //Connecting to database
        con = DBconnect.connect();
        
        tableload();
    }
    
    public void tableload(){
        
        try {
            String sql = "SELECT ExpenseID,Month,WaterBill,TelephoneBill,ElectricityBill,Salary,Maintenance,TotalExpenses FROM expenses";
            pst = con.prepareStatement(sql);
            rs =  pst.executeQuery();
            
            exp_table.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
           
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        expid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_water = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_tele = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_elec = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_sal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_maintain = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        Add_btn = new javax.swing.JButton();
        Update_btn = new javax.swing.JButton();
        Reset_btn = new javax.swing.JButton();
        Delete_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        exp_table = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        c_month = new com.toedter.calendar.JMonthChooser();
        Reset_btn1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(1354, 522));
        setPreferredSize(new java.awt.Dimension(1354, 522));
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1352, 494));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("EXPENSES");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_Back_131811.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EXPENSE ID                   :");

        expid.setEditable(false);
        expid.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MONTH                          :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("WATER BILL                   :");

        txt_water.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_water.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TELEPHONE BILL            :");

        txt_tele.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ELCTRICITY BILL            :");

        txt_elec.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EMPLOYEE SALARY        :");

        txt_sal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("VEHICLE MAINTENANCE :");

        txt_maintain.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_maintain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maintainActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL EXPENSE            :");

        txt_total.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Add_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        Add_btn.setText("ADD");
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });

        Update_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit.png"))); // NOI18N
        Update_btn.setText("UPDATE");
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        Reset_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reset_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        Reset_btn.setText("RESET");
        Reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_btnActionPerformed(evt);
            }
        });

        Delete_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        Delete_btn.setText("DELETE");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });

        exp_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        exp_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EXPENSE ID", "MONTH", "WATER BILL", "TELEPHONE BILL", "ELECTRICITY BILL", "EMPLOYEE SALARY", "MAINTENANCE", "TOTAL EXPENSE"
            }
        ));
        exp_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exp_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(exp_table);

        c_month.setMinimumSize(new java.awt.Dimension(100, 24));

        Reset_btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reset_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/calculate.png"))); // NOI18N
        Reset_btn1.setText("CALCULATE");
        Reset_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(expid)
                                        .addComponent(txt_water)
                                        .addComponent(txt_tele)
                                        .addComponent(txt_elec)
                                        .addComponent(txt_maintain)
                                        .addComponent(txt_sal)
                                        .addComponent(txt_total)
                                        .addComponent(c_month, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10))
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Reset_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(Delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(Reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jButton1))
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(expid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_month, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_water, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tele, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_elec, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_maintain, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Add_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Update_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Reset_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Update Button
    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed

        int p = JOptionPane.showConfirmDialog(null, "Do you really want to UPDATE?");
        
        if(p == 0){
            
        String id = expid.getText();
        String waterBill = txt_water.getText();
        String teleBill = txt_tele.getText();
        String elecBill = txt_elec.getText();
        String salary = txt_sal.getText();
        String maintain = txt_maintain.getText();
        String totalExpense = txt_total.getText();
        
            
        try {
            DBconnect.connect().createStatement().executeUpdate("UPDATE expenses SET  WaterBill = '" + waterBill + "', TelephoneBill = '" + teleBill + "', ElectricityBill = '" + elecBill + "', salary = '" + salary + "', Maintenance = '" + maintain + "', TotalExpenses = '" + totalExpense + "' WHERE ExpenseID = '" + id + "' ");
            tableload();
            JOptionPane.showMessageDialog(null, "Update Successfully");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Update Unsuccessfully");
            JOptionPane.showMessageDialog(rootPane, e);
        }
            
        }     
        
        
    }//GEN-LAST:event_Update_btnActionPerformed

    private void txt_maintainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maintainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maintainActionPerformed

    //Reset Button
    private void Reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_btnActionPerformed
        
         expid.setText(null);
        txt_water.setText(null);
        txt_tele.setText(null);
        txt_elec.setText(null);
        txt_sal.setText(null);
        txt_maintain.setText(null);
        txt_total.setText(null);
        
    }//GEN-LAST:event_Reset_btnActionPerformed

    private void txt_salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salActionPerformed

    //Moving back in home
    Finance_Home fin_home;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (fin_home == null) {

            jDesktopPane2.removeAll();
            Finance_Home home = new Finance_Home();
            jDesktopPane2.add(home).setVisible(true);
        } else {
            jDesktopPane2.removeAll();
            jDesktopPane2.add(fin_home).setVisible(true);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //Calculate Button
    private void Reset_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_btn1ActionPerformed

        int totalExp = Integer.parseInt(txt_water.getText()) + Integer.parseInt(txt_tele.getText()) + Integer.parseInt(txt_elec.getText()) + Integer.parseInt(txt_sal.getText()) + Integer.parseInt(txt_maintain.getText());

        txt_total.setText(String.valueOf(totalExp));


    }//GEN-LAST:event_Reset_btn1ActionPerformed

    //Add Button
    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed

        int month = c_month.getMonth()+1;
        String waterBill = txt_water.getText();
        String teleBill = txt_tele.getText();
        String elecBill = txt_elec.getText();
        String salary = txt_sal.getText();
        String maintain = txt_maintain.getText();
        String totalExpense = txt_total.getText().toString();
        
        if (waterBill.equals("") || teleBill.equals("") || elecBill.equals("") || salary.equals("") || maintain.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all the FIELDS");
        } else if (!waterBill.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Invalide Format For Water Bill");
        } else if (!teleBill.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Invalide Format For Telephone Bill");
        } else if (!elecBill.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Invalide Format For Electricity Bill");
        } else if (!salary.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Invalide Format For Salary");
        } else if (!maintain.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Invalide Format For Vehical Mintenance");
        } else {
        
        
            try {
            
                String q = "INSERT INTO expenses (Month,WaterBill,TelephoneBill,ElectricityBill,Salary,Maintenance,TotalExpenses) values ('"+ month +"', '"+ waterBill +"', '"+ teleBill +"', '"+ elecBill +"', '"+ salary +"', '"+ maintain +"', '"+ totalExpense +"')";
                pst = con.prepareStatement(q);
                pst.execute();
            
                tableload();
            
                JOptionPane.showMessageDialog(null, "Monthly Expense Inserted!");
            
            } catch (Exception e) {
            
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
    }//GEN-LAST:event_Add_btnActionPerformed

    //Delete Button
    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to the DELETE");
        
        if (p == 0){
            
             String id = expid.getText();
             
             try{
                 
                 String q = "DELETE FROM expenses WHERE ExpenseID = '" + id + "'";
                 pst = con.prepareStatement(q);
                 pst.execute();
                 
                 tableload();
                 
                 JOptionPane.showMessageDialog(null, "DELETED Successfull!");
                 
             }catch(Exception e){
                 e.printStackTrace();
             }
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Cancel The Request");
        }
        
    }//GEN-LAST:event_Delete_btnActionPerformed

    private void exp_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exp_tableMouseClicked
        
        
        int r = exp_table.getSelectedRow();
        
        String id = exp_table.getValueAt(r, 0).toString();
        String month = exp_table.getValueAt(r, 1).toString();
        String water = exp_table.getValueAt(r, 2).toString();
        String tele = exp_table.getValueAt(r, 3).toString();
        String elec = exp_table.getValueAt(r, 4).toString();
        String salary = exp_table.getValueAt(r, 5).toString();
        String main = exp_table.getValueAt(r, 6).toString();
        String totexp = exp_table.getValueAt(r, 7).toString();
        
        expid.setText(id);
        c_month.setMonth(Integer.parseInt(month));
        txt_water.setText(water);
        txt_tele.setText(tele);
        txt_elec.setText(elec);
        txt_sal.setText(salary);
        txt_maintain.setText(main);
        txt_total.setText(totexp);
    }//GEN-LAST:event_exp_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn;
    private javax.swing.JButton Delete_btn;
    private javax.swing.JButton Reset_btn;
    private javax.swing.JButton Reset_btn1;
    private javax.swing.JButton Update_btn;
    private com.toedter.calendar.JMonthChooser c_month;
    private javax.swing.JTable exp_table;
    private javax.swing.JTextField expid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txt_elec;
    private javax.swing.JTextField txt_maintain;
    private javax.swing.JTextField txt_sal;
    private javax.swing.JTextField txt_tele;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_water;
    // End of variables declaration//GEN-END:variables
}
