/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finance;

import static Student.USM_MAIN_INTERFACE.jDesktopPane2;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Yelani
 */
public class Finance_Profit extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Finance_Profit
     */
    public Finance_Profit() {
        initComponents();

        con = DBconnect.connect();
        
        tableload();
    }
    
    public void tableload(){
        
        try {
            String sql = "SELECT ProfitID,Month,MonthlyFee,MonthlyExpenses,MonthlyProfit FROM profit";
            pst = con.prepareStatement(sql);
            rs =  pst.executeQuery();
            
            profit_table.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
           
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_pid = new javax.swing.JTextField();
        txt_totexp = new javax.swing.JTextField();
        txt_totfee = new javax.swing.JTextField();
        txt_totprofit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Update_btn = new javax.swing.JButton();
        Add_btn = new javax.swing.JButton();
        Reset_btn = new javax.swing.JButton();
        Delete_btn = new javax.swing.JButton();
        Update_btn1 = new javax.swing.JButton();
        Update_btn2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        profit_table = new javax.swing.JTable();
        c_m3 = new com.toedter.calendar.JMonthChooser();
        jSeparator4 = new javax.swing.JSeparator();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(1354, 522));
        setPreferredSize(new java.awt.Dimension(1354, 522));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1352, 494));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PROFIT");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_Back_131811.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROFIT ID                              :");

        txt_pid.setEditable(false);
        txt_pid.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_totexp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_totexp.setToolTipText("");

        txt_totfee.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_totprofit.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MONTHLY PROFIT           :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MONTHLY FEES                :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MONTHLY EXPENSES        :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MONTH                             :");

        Update_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/calculate.png"))); // NOI18N
        Update_btn.setText("CALCULATE");
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        Add_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        Add_btn.setText("ADD");
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });

        Reset_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reset_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        Reset_btn.setText("RESET");
        Reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_btnActionPerformed(evt);
            }
        });

        Delete_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        Delete_btn.setText("DELETE");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });

        Update_btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Update_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit.png"))); // NOI18N
        Update_btn1.setText("UPDATE");
        Update_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btn1ActionPerformed(evt);
            }
        });

        Update_btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Update_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Adobe_PDF_file_icon_32x32.png"))); // NOI18N
        Update_btn2.setText("PDF");
        Update_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btn2ActionPerformed(evt);
            }
        });

        profit_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PROFIT IT", "MONTH", "MONTHLY EXPENSES", "MONTHLY FEE", "MONTHLY PROFIT"
            }
        ));
        profit_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profit_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(profit_table);

        c_m3.setMinimumSize(new java.awt.Dimension(100, 24));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1308, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_totexp)
                                    .addComponent(txt_pid)
                                    .addComponent(txt_totfee)
                                    .addComponent(txt_totprofit)
                                    .addComponent(c_m3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(Add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(Update_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(Update_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(Delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(Reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 47, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jButton1))
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(c_m3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_totexp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_totfee, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_totprofit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_btn)
                    .addComponent(Update_btn1)
                    .addComponent(Update_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_btn)
                    .addComponent(Reset_btn))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1351, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Add Button
    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed

        int month3 = c_m3.getMonth()+1;
        String monthlyExp = txt_totfee.getText();
        String monthlyFee = txt_totexp.getText();
        String profit = txt_totprofit.getText();
       
        
        try {
            
            String q2 = "INSERT INTO profit (Month,MonthlyFee,MonthlyExpenses,MonthlyProfit) values ('"+ month3 +"', '"+ monthlyExp +"', '"+ monthlyFee +"', '"+ profit +"')";
            pst = con.prepareStatement(q2);
            pst.execute();
            
            tableload();
            
            JOptionPane.showMessageDialog(null, "Monthly Profit Inserted!");
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_Add_btnActionPerformed

    //Calculate Button
    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
        int totalProfit = Integer.parseInt(txt_totfee.getText()) - Integer.parseInt(txt_totexp.getText());
        txt_totprofit.setText(String.valueOf(totalProfit));
    }//GEN-LAST:event_Update_btnActionPerformed

    private void Update_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btn2ActionPerformed

    }//GEN-LAST:event_Update_btn2ActionPerformed

    //Moving back into home
    Finance_Home fin_home;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (fin_home == null) {

            jDesktopPane2.removeAll();
            Finance_Home home = new Finance_Home();
            jDesktopPane2.add(home).setVisible(true);
        } else {
            jDesktopPane2.removeAll();
            jDesktopPane2.add(fin_home).setVisible(true);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //Update Button
    private void Update_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btn1ActionPerformed
        
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to UPDATE?");
        
        if(p == 0){
            
        String id = txt_pid.getText();
        String mfee = txt_totfee.getText();
        String mexp = txt_totexp.getText();
        String totprofit = txt_totprofit.getText();
        
        
            
        try {
            DBconnect.connect().createStatement().executeUpdate("UPDATE profit SET  MonthlyFee = '" + mfee + "', MonthlyExpenses = '" + mexp + "', MonthlyProfit = '" + totprofit + "' WHERE ProfitID = '" + id + "' ");
            tableload();
            JOptionPane.showMessageDialog(null, "Update Successfully");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Update Unsuccessfully");
            JOptionPane.showMessageDialog(rootPane, e);
        }
            
        }     
        
    }//GEN-LAST:event_Update_btn1ActionPerformed

    //Delete Button
    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
        
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to the DELETE");
        
        if (p == 0){
            
             String id = txt_pid.getText();
             
             try{
                 
                 String q = "DELETE FROM profit WHERE ProfitID = '" + id + "'";
                 pst = con.prepareStatement(q);
                 pst.execute();
                 
                 tableload();
                 
                 JOptionPane.showMessageDialog(null, "DELETED Successfull!");
                 
             }catch(Exception e){
                 e.printStackTrace();
             }
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Cancel The Request");
        }
        
        
    }//GEN-LAST:event_Delete_btnActionPerformed

    //Reset Button
    private void Reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_btnActionPerformed
        
        txt_pid.setText(null);
        txt_totfee.setText(null);
        txt_totexp.setText(null);
        txt_totprofit.setText(null);
        
        
    }//GEN-LAST:event_Reset_btnActionPerformed

    private void profit_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profit_tableMouseClicked
        
         int r = profit_table.getSelectedRow();
        
        String id = profit_table.getValueAt(r, 0).toString();
        String month = profit_table.getValueAt(r, 1).toString();
        String mfee = profit_table.getValueAt(r, 2).toString();
        String mexp = profit_table.getValueAt(r, 3).toString();
        String mprofit = profit_table.getValueAt(r, 4).toString();
        
        
        
        txt_pid.setText(id);
        c_m3.setMonth(Integer.parseInt(month));
        txt_totfee.setText(mfee);
        txt_totexp.setText(mexp);
        txt_totprofit.setText(mprofit);
        
    }//GEN-LAST:event_profit_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn;
    private javax.swing.JButton Delete_btn;
    private javax.swing.JButton Reset_btn;
    private javax.swing.JButton Update_btn;
    private javax.swing.JButton Update_btn1;
    private javax.swing.JButton Update_btn2;
    private com.toedter.calendar.JMonthChooser c_m3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable profit_table;
    private javax.swing.JTextField txt_pid;
    private javax.swing.JTextField txt_totexp;
    private javax.swing.JTextField txt_totfee;
    private javax.swing.JTextField txt_totprofit;
    // End of variables declaration//GEN-END:variables
}
