/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import EmpManagement.EmpHome;
import Faculty.FacultyManagement;
import Student.Home_Buttons_Interface;
import static Student.USM_MAIN_INTERFACE.jDesktopPane2;
import Student.STUDENT_HOME2;
import finance.Finance_Home;
import javax.swing.JOptionPane;

/**
 *
 * @author Chaveen
 */
public class UserLogin extends javax.swing.JInternalFrame {

    UserLogin ulog;
    AddNewUser addNew;
    EditUser editUser;
    RemoveUser removeUser;

    EmpHome emp;
    FacultyManagement fac;
    STUDENT_HOME2 stu;
    Finance_Home fin;
    Admin_home ad;

    /**
     * Creates new form NewJInternalFrame
     */
    public UserLogin() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Username_txt = new javax.swing.JTextField();
        signIn = new javax.swing.JButton();
        signUp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(1354, 522));
        setPreferredSize(new java.awt.Dimension(1354, 522));

        password.setBackground(new java.awt.Color(0, 102, 102));
        password.setPreferredSize(new java.awt.Dimension(1354, 522));

        jRadioButton2.setBackground(new java.awt.Color(0, 102, 102));
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Forgot password?");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USER LOGIN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERNAME\n");
        jLabel2.setMaximumSize(new java.awt.Dimension(96, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(96, 17));
        jLabel2.setPreferredSize(new java.awt.Dimension(96, 17));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD\n");

        Username_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Username_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_txtActionPerformed(evt);
            }
        });

        signIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signIn.setText("Sign in");
        signIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signIn.setNextFocusableComponent(Username_txt);
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });
        signIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signInKeyPressed(evt);
            }
        });

        signUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signUp.setText("Sign Up");
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });

        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Home.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout passwordLayout = new javax.swing.GroupLayout(password);
        password.setLayout(passwordLayout);
        passwordLayout.setHorizontalGroup(
            passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordLayout.createSequentialGroup()
                .addGap(522, 522, 522)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(398, 398, 398)
                .addComponent(jButton1)
                .addGap(0, 34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(492, 492, 492))
            .addGroup(passwordLayout.createSequentialGroup()
                .addGroup(passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordLayout.createSequentialGroup()
                        .addGap(474, 474, 474)
                        .addGroup(passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2)))
                    .addGroup(passwordLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        passwordLayout.setVerticalGroup(
            passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed

        String un = Username_txt.getText();
        String pw = String.valueOf(jPasswordField1.getPassword());

        if (un.equalsIgnoreCase("employee") && pw.equals("employee")) {
            JOptionPane.showMessageDialog(rootPane, "Success");
            if (emp == null) {
                jDesktopPane2.removeAll();
                EmpHome ad1 = new EmpHome();
                jDesktopPane2.add(ad1).setVisible(true);
            } else {
                jDesktopPane2.removeAll();
                jDesktopPane2.add(emp).setVisible(true);
            }
        } else if (un.equalsIgnoreCase("faculty") && pw.equals("faculty")) {
            JOptionPane.showMessageDialog(rootPane, "Success");
            if (fac == null) {
                jDesktopPane2.removeAll();
                FacultyManagement ad1 = new FacultyManagement();
                jDesktopPane2.add(ad1).setVisible(true);
            } else {
                jDesktopPane2.removeAll();
                jDesktopPane2.add(fac).setVisible(true);
            }
        } else if (un.equalsIgnoreCase("s") && pw.equals("s")) {
            JOptionPane.showMessageDialog(rootPane, "Success");
            if (stu == null) {
                jDesktopPane2.removeAll();
                STUDENT_HOME2 ad1 = new STUDENT_HOME2();
                jDesktopPane2.add(ad1).setVisible(true);
            } else {
                jDesktopPane2.removeAll();
                jDesktopPane2.add(stu).setVisible(true);
            }
        } else if (un.equalsIgnoreCase("finance") && pw.equals("finance")) {
            JOptionPane.showMessageDialog(rootPane, "Success");
            if (fin == null) {
                jDesktopPane2.removeAll();
                Finance_Home ad1 = new Finance_Home();
                jDesktopPane2.add(ad1).setVisible(true);
            } else {
                jDesktopPane2.removeAll();
                jDesktopPane2.add(fin).setVisible(true);
            }
        } else if (un.equalsIgnoreCase("admin") && pw.equals("admin")) {
            JOptionPane.showMessageDialog(rootPane, "Success");
            if (fin == null) {
                jDesktopPane2.removeAll();
                Admin_home ad2 = new Admin_home();
                jDesktopPane2.add(ad2).setVisible(true);
            } else {
                jDesktopPane2.removeAll();
                jDesktopPane2.add(ad).setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Incorrect username or password.");

        }
    }//GEN-LAST:event_signInActionPerformed

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed

        if (addNew == null) {
            jDesktopPane2.removeAll();
            AddNewUser ad1 = new AddNewUser();
            jDesktopPane2.add(ad1).setVisible(true);
        } else {
            jDesktopPane2.removeAll();
            jDesktopPane2.add(addNew).setVisible(true);
        }
    }//GEN-LAST:event_signUpActionPerformed

    Student.Home_Buttons_Interface hm;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (hm == null) {

            jDesktopPane2.removeAll();
            Home_Buttons_Interface h1 = new Home_Buttons_Interface();
            jDesktopPane2.add(h1).setVisible(true);
        } else {
            jDesktopPane2.removeAll();
            jDesktopPane2.add(hm).setVisible(true);

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void Username_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_txtActionPerformed
        jPasswordField1.grabFocus();
    }//GEN-LAST:event_Username_txtActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        signIn.grabFocus();
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void signInKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signInKeyPressed
        String un = Username_txt.getText();
        String pw = String.valueOf(jPasswordField1.getPassword());

        if (un.equalsIgnoreCase("employee") && pw.equals("employee")) {
            JOptionPane.showMessageDialog(rootPane, "Success");
            if (emp == null) {
                jDesktopPane2.removeAll();
                EmpHome ad1 = new EmpHome();
                jDesktopPane2.add(ad1).setVisible(true);
            } else {
                jDesktopPane2.removeAll();
                jDesktopPane2.add(emp).setVisible(true);
            }
        } else if (un.equalsIgnoreCase("faculty") && pw.equals("faculty")) {
            JOptionPane.showMessageDialog(rootPane, "Success");
            if (fac == null) {
                jDesktopPane2.removeAll();
                FacultyManagement ad1 = new FacultyManagement();
                jDesktopPane2.add(ad1).setVisible(true);
            } else {
                jDesktopPane2.removeAll();
                jDesktopPane2.add(fac).setVisible(true);
            }
        } else if (un.equalsIgnoreCase("s") && pw.equals("s")) {
            JOptionPane.showMessageDialog(rootPane, "Success");
            if (stu == null) {
                jDesktopPane2.removeAll();
                STUDENT_HOME2 ad1 = new STUDENT_HOME2();
                jDesktopPane2.add(ad1).setVisible(true);
            } else {
                jDesktopPane2.removeAll();
                jDesktopPane2.add(stu).setVisible(true);
            }
        } else if (un.equalsIgnoreCase("finance") && pw.equals("finance")) {
            JOptionPane.showMessageDialog(rootPane, "Success");
            if (fin == null) {
                jDesktopPane2.removeAll();
                Finance_Home ad1 = new Finance_Home();
                jDesktopPane2.add(ad1).setVisible(true);
            } else {
                jDesktopPane2.removeAll();
                jDesktopPane2.add(fin).setVisible(true);
            }
        } else if (un.equalsIgnoreCase("admin") && pw.equals("admin")) {
            JOptionPane.showMessageDialog(rootPane, "Success");
            if (fin == null) {
                jDesktopPane2.removeAll();
                Admin_home ad2 = new Admin_home();
                jDesktopPane2.add(ad2).setVisible(true);
            } else {
                jDesktopPane2.removeAll();
                jDesktopPane2.add(ad).setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Incorrect username or password.");
        }
    }//GEN-LAST:event_signInKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Username_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel password;
    private javax.swing.JButton signIn;
    private javax.swing.JButton signUp;
    // End of variables declaration//GEN-END:variables
}
